#ifndef codatom
#define codatom
// Coduri lexicale
#define MAI_MIC_EGAL    100
#define DIFERIT         101
#define MAI_MIC_STRICT  102
#define MAI_MARE_EGAL   103
#define MAI_MARE_STRICT 104
#define ATRIBUIRE       105
#define DOUA_PUNCTE     106
#define REAL_EXPONENT   107
#define REAL_SIMPLU     108
#define INTREG_BAZA     109
#define INTREG_SIMPLU   110
#define VECTOR          111
#define SIR_CAR         112
#define CAR             113
#define COMENTARIU      114      //  nu e nevoie
#define IDENTIFICATOR   115
#define KEYWORD         116
#define PARANTEZA_S     117
#define PARANTEZA_PS    118
#define PUNCT_VIRGULA   119
#define PLUS            120
#define MINUS           121
#define INMULTIT        122
#define IMPARTIT        123
#define EGAL            124
#define FILE_END        125
#define PARANTEZA_PD    126
#define PARANTEZA_D     127
#define VIRGULA         128
#define PUNCT           129

#endif